default_config:

# Example configuration.yaml entry
input_number:
  weight:
    name: Weight
    initial: 70
    min: 10
    max: 200
    step: 0.1
  impedance:
    name: Impedance
    initial: 400
    min: 0
    max: 3000
    step: 1

bodymiscale:
  test:
    sensors:
      weight: input_number.weight
      impedance: input_number.impedance
    height: 180
    born: "1990-01-01"
    gender: "male"
    model_miscale: "181B"

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
#  wait: true
